name: Debug CI
on:
  push:
    branches: [ debug-ci ]
permissions:
  actions: read
  contents: write
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          gh run list --limit 3
          FAILED_RUN=$(gh run list --status failure --json databaseId --jq '.[0].databaseId')
          gh run view $FAILED_RUN --log > ci.log
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ci.log
          git commit -m "Add ci log"
          git push -f origin HEAD:debug-ci-result
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
